[project]
name = "demomcp"
version = "0.1.0"
description = "Demo MCP project"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=1.1.2",
    "streamlit>=1.53.1",
    "typing-extensions>=4.15.0",
]

[tool.uv]

[dependency-groups]
dev = [
    "mcp-use>=1.6.0",
]

